# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aut_ciudadnacimiento', models.CharField(max_length=25)),
                ('aut_fechanacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edi_nombre', models.CharField(max_length=25)),
                ('edi_codigopostal', models.CharField(max_length=10)),
                ('edi_direccion', models.CharField(max_length=50)),
                ('edi_telefono', models.CharField(max_length=10)),
                ('edi_email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_titulo', models.CharField(max_length=40)),
                ('lib_fechapublicacion', models.DateField()),
                ('lib_numpaginas', models.IntegerField()),
                ('lib_idioma', models.CharField(max_length=15)),
                ('lib_resumen', models.CharField(max_length=200)),
                ('lib_link', models.CharField(max_length=100)),
                ('autor', models.ManyToManyField(to='Biblioteca.Autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca.Categoria')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca.Editorial')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_nombre', models.CharField(max_length=25)),
                ('per_apellido', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_fecprestamo', models.DateField()),
                ('pre_fecdevolucion', models.DateField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca.Libro')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usu_telefono', models.CharField(max_length=10)),
                ('usu_direccion', models.CharField(max_length=50)),
                ('usu_email', models.CharField(max_length=50)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='prestamos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca.Usuario'),
        ),
        migrations.AddField(
            model_name='autor',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca.Persona'),
        ),
    ]
